spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/demo?useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
        allow: 127.0.0.1,localhost
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.css,/druid/*"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  redis:
    host: localhost
    port: 6379
    database: 2
    # password:
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always

jwt:
  secret: /YFZnYU4eBc3BCDyHTaEZSD43qBKSrLNssHkTxzgQ5k=
  expiration: 3600000 # 1小时

aws:
  region: cn-northwest-1
  access-key-id: AKIARS2X7EPDZLFULMNH
  secret-access-key: xbsmBesyrgQnhkAHq54T0l7Df2AL67mfMVbelOeb
  s3:
    bucket: cn-red-ana-test-s3-b01

aliyun:
  oss:
    endpoint: dummy-endpoint
    bucket: dummy-bucket
  access-key-id: dummy-access-key-id
  secret-access-key: dummy-secret-access-key

local:
  path: /var/app/files

cloud:
  provider: aws
